from .base import BaseAgent
from typing import Dict, Any
from datetime import datetime

class ReportAgent(BaseAgent):
    """Agent responsible for final report generation"""
    
    def __init__(self):
        super().__init__(temperature=0.2)
    
    def process(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """Combine all outputs into final structured report"""
        print("📊 Report Agent: Creating final report...")
        
        report = f"""# 🎬 YouTube Video Summary Report
Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## 📌 VIDEO INFORMATION
**URL:** {state.get('url', 'N/A')}
**Video ID:** {state.get('video_id', 'N/A')}

---

## 🧠 EXECUTIVE SUMMARY

{state.get('summary', 'No summary available')}

---

## 🔥 KEY INSIGHTS & TAKEAWAYS

{state.get('insights', 'No insights available')}

---

## ❓ QUESTIONS & DISCUSSION POINTS

{state.get('questions', 'No questions available')}

---

## ✅ ACTIONABLE NEXT STEPS

Based on this video, you can:
1. **Review** the key insights and take notes
2. **Answer** the comprehension questions to test understanding
3. **Discuss** the talking points with peers/colleagues
4. **Apply** the concepts in your own work/studies

---

*Generated by AI YouTube Summarizer using LangGraph Multi-Agent System*
"""
        
        return {
            "final_report": report,
            "processing_stage": "completed"
        }